# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoreDeepStyleDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoreSegmentDemo
  pod 'DoreCoreAI','1.0.18'
  pod 'DoreDeepStyle','1.0.17'

end
 
